name: 'zoo_analytics'
version: '1.0.0'
config-version: 2

profile: 'zoo_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  
models:
  zoo_analytics:
    zoo:
      +materialized: table
      +post-hook: "COPY (SELECT * FROM {{ this }}) TO 'results/{{ this.name }}.csv' (HEADER, DELIMITER ',')"

seeds:
  zoo_analytics:
    +quote_columns: true

vars:
  project_name: 'zoo_analytics'

