version: 2

sources:
  - name: act_system
    description: "Animal Care Tool database"
    database: act_system
    schema: main
    tables:
      - name: animals
      - name: species
      - name: enclosures
      - name: feeding_schedules

  - name: vrm_system
    description: "Visitor Relationship Management database"
    database: vrm_system
    schema: main
    tables:
      - name: visitors
      - name: events
      - name: tickets


